apiVersion: v1
data:
  "csi-migration": "true" # csi-migration feature is only available for vSphere 7.0U1
  "csi-auth-check": "true"
  "online-volume-extend": "true"
  "block-volume-snapshot": "true"
  "improved-volume-topology": "false" # operator will set this value to true if cluster supports CSI topology
  "use-csinode-id": "true"
kind: ConfigMap
metadata:
  name: internal-feature-states.csi.vsphere.vmware.com
  namespace: openshift-cluster-csi-drivers
